### ISSUE TITLE
no module named 'pyocr'

### ISSUE THREAD

**Issue by Chankit8** [1114319054/cet46query#2]
按经验贴安装完tesseract后运行出现
![360 20180824142815894](https://user-images.githubusercontent.com/35122233/44568569-fa923e80-a7a9-11e8-9a9f-4046df92d8b0.jpg)
请问该如何解决

**Comment by 1114319054** [comment]
我使用的是tesseract 3.05.01dev版本，可能4.0版本存在问题，可关注以下问题：
openpaperwork/pyocr#99
