### ISSUE TITLE
好像跑不起来

### ISSUE THREAD

**Issue by jiangjunlin1234** [1114319054/cet46query#3]
File "C:/Workspaces/test4/query.py", line 133, in <module>
    v=two_value(name)

**Comment by jiangjunlin1234** [comment]
C:\Users\admin\venv\pythonSDK\Scripts\python.exe C:/Workspaces/test4/query.py
当前考场号为01  当前座位号为1
Traceback (most recent call last):
  File "C:/Workspaces/test4/query.py", line 133, in <module>
    v=two_value(name)
  File "C:/Workspaces/test4/query.py", line 73, in two_value
    builder=pyocr.builders.TextBuilder()
  File "F:\Anaconda3\lib\site-packages\pyocr\tesseract.py", line 367, in image_to_string
    raise TesseractError(status, errors)
pyocr.error.TesseractError: (1, b"Error, unknown command line argument '-psm'\r\n")

进程完成，退出码 1

**Comment by 1114319054** [comment]
我使用的是tesseract 3.05.01dev版本，可能4.0版本存在问题，可关注以下问题：
https://github.com/openpaperwork/pyocr/issues/99

**Comment by jiangjunlin1234** [comment]
跑起来了，但是好像要先提供十一位的准考证号，如果遇到一百考场该怎么解决呢

**Comment by 1114319054** [comment]
不是这样的，提供前10位准考证号即可，考场号如果是100不会补0，座位号如果是两位数，也不会补0。

**Comment by 1114319054** [comment]
是有一些问题，我没有考虑考场号是个位的情况，我回去修改一下

**Comment by jiangjunlin1234** [comment]
恩恩，我刚刚用正确的准考证号去试了下，考场为95座位为30，但是并没有结果。

当前考场号为095  当前座位号为30
3823
24eb4c02fd104cceb3bf556a25805e9a.png
http://cache.neea.edu.cn/Imgs.do?c=CET&ik=430421181109530&t=0.9645281504781837
您查询的结果为空！

**Comment by 1114319054** [comment]
姓名变量修改为自己姓名了吗？

**Comment by jiangjunlin1234** [comment]
lower=1
upper=30
#这一部分修改成个人信息即可
roomId=95
seatId=28
username='xxx'
areaId='4304211811'

**Comment by 1114319054** [comment]
username也需要修改为姓名

**Comment by jiangjunlin1234** [comment]
改了的，别人的姓名我这里就没有贴出来了

**Comment by 1114319054** [comment]
我感觉信息会不会有错误，根据这个信息在官网上能查到吗？

**Comment by jiangjunlin1234** [comment]
能查到的，我测试了好几遍才回您的

**Comment by 1114319054** [comment]
您这是查询四级成绩吗？抱歉，当时构造请求都是按六级构造的，我回去修改一下

**Comment by jiangjunlin1234** [comment]
原来是这样，我刚刚看代码的时候也发现只返回六级的值

**Comment by jiangjunlin1234** [comment]
if type == 1:
    Type = 'CET4_181_DANGCI,'
elif type == 2:
Type = 'CET6_181_DANGCI,'
加上这个
还有判断一下初始考场号为个位的情况，这个程序就ok了

**Comment by 1114319054** [comment]
已解决，谢谢
