### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by jinaeiu** [1114319054/cet46query#4]
我运行的时候出现了“IndexError: list index out of range”这个错误，试着百度然后自己调试，可是都没有用，请问这种情况应该怎么改？

**Comment by 1114319054** [comment]
能附一下报错的图吗？

**Comment by jinaeiu** [comment]
昨天那个问题没有了  但是刚刚运行的时候一直循环
![1](https://user-images.githubusercontent.com/17545898/44694019-e26a3a00-aa9d-11e8-9584-71c7e6d158d0.png)

**Comment by 1114319054** [comment]
这个错误更换一下tesseract的版本即可

**Comment by jinaeiu** [comment]
那我应该用哪个版本？  我下的是4.0版的

**Comment by 1114319054** [comment]
我使用的是tesseract 3.05.01dev版本，可能4.0版本存在问题，可关注以下问题：
openpaperwork/pyocr#99

**Comment by jinaeiu** [comment]
好的  谢谢你！

**Comment by jinaeiu** [comment]
不好意思，再次打扰一下，版本问题已解决，但是为什么循环不执行？
![image](https://user-images.githubusercontent.com/17545898/44694680-85708300-aaa1-11e8-87f2-24c3bd80e5ff.png)

**Comment by 1114319054** [comment]
我设计的是死循环，Ctrl c退出，验证码通常试几次才会正确

**Comment by jinaeiu** [comment]
哦哦  那这种方式在不清楚座位号和考场号的情况下那会运行很久？

**Comment by 1114319054** [comment]
是的，相当于一个一个准考证号去试

**Comment by Yanjiachan** [comment]
@1114319054 我用的是3.05.02的版本也是报错
![image](https://user-images.githubusercontent.com/25785265/44700804-cd9d9e80-aabd-11e8-9ee3-7c1d25416b54.png)
麻烦看一下

**Comment by Yanjiachan** [comment]
@1114319054 
![image](https://user-images.githubusercontent.com/25785265/44702853-f2970f00-aac7-11e8-87d3-629f2fad7dfd.png)不知道如何解决

**Comment by 1114319054** [comment]
问一下，你设置tesseract的环境变量了吗？
